import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import type { AppConfig } from "../types.js";
import { F5XcClient, handleApiError } from "../services/f5-xc-client.js";
import { DEFAULT_PAGE_SIZE, MAX_PAGE_SIZE, CHARACTER_LIMIT } from "../constants.js";

// Customer Edge (CE) lifecycle:
//   - Registration token: POST /api/register/namespaces/system/tokens  (body: {metadata: {name, namespace:"system"}, spec:{}})
//   - Site list/status:   GET  /api/config/namespaces/system/sites     (read-only — CE registers itself, we only observe)
//   - Site delete:        DELETE /api/config/namespaces/system/sites/{name}
//   - Cloud CE deployment is primarily Terraform-driven via the volterraedge/volterra provider.
// Token create quirk: body must use {metadata: {name, namespace}, spec:{}} wrapper, not bare {name}.
//
// Terraform HCL generation for CE is done via this tool, not terraform-runner.ts,
// because CE config varies significantly by cloud provider.

const PaginationSchema = {
  page_start: z.number().int().min(0).default(0).describe("Pagination offset"),
  page_limit: z.number().int().min(1).max(MAX_PAGE_SIZE).default(DEFAULT_PAGE_SIZE).describe("Max items to return"),
};

const DryRunSchema = {
  dryRun: z.boolean().optional().describe("Preview the API call without executing it"),
};

function truncate(text: string): string {
  if (text.length <= CHARACTER_LIMIT) return text;
  return text.slice(0, CHARACTER_LIMIT) + `\n\n[Truncated. Use page_start/page_limit to paginate.]`;
}

function generateAzureHcl(params: {
  tenant: string;
  siteName: string;
  token: string;
  region: string;
  resourceGroup: string;
  vnetName: string;
  subnetName: string;
  siteLatitude: number;
  siteLongitude: number;
}): string {
  return `# F5 XC Customer Edge — Azure
# Generated by F5 XC MCP Server
# Provider: volterraedge/volterra
# Reference: https://registry.terraform.io/providers/volterraedge/volterra/latest/docs

terraform {
  required_providers {
    volterra = {
      source  = "volterraedge/volterra"
      version = ">= 0.11"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.0"
    }
  }
}

provider "volterra" {
  api_p12_file = var.api_p12_file
  url          = "https://${params.tenant}.console.ves.volterra.io/api"
}

provider "azurerm" {
  features {}
}

variable "api_p12_file" {
  description = "Path to F5 XC .p12 credentials file"
  type        = string
}

resource "volterra_azure_vnet_site" "${params.siteName.replace(/-/g, "_")}" {
  name      = "${params.siteName}"
  namespace = "system"

  azure_region  = "${params.region}"
  resource_group = "${params.resourceGroup}"

  vnet {
    existing_vnet {
      resource_group = "${params.resourceGroup}"
      vnet_name      = "${params.vnetName}"
    }
  }

  ingress_egress_gw {
    azure_certified_hw = "azure-byol-multi-nic-voltmesh"
    az_nodes {
      azure_az  = "1"
      disk_size = 80

      inside_subnet {
        subnet {
          subnet_resource_grp = "${params.resourceGroup}"
          vnet_resource_group = true
          subnet_name         = "${params.subnetName}-inside"
        }
      }
      outside_subnet {
        subnet {
          subnet_resource_grp = "${params.resourceGroup}"
          vnet_resource_group = true
          subnet_name         = "${params.subnetName}-outside"
        }
      }
    }
  }

  coordinates {
    latitude  = ${params.siteLatitude}
    longitude = ${params.siteLongitude}
  }

  registration_token = "${params.token}"
}

output "site_name" {
  value = volterra_azure_vnet_site.${params.siteName.replace(/-/g, "_")}.name
}
`;
}

function generateAwsHcl(params: {
  tenant: string;
  siteName: string;
  token: string;
  region: string;
  vpcId: string;
  siteLatitude: number;
  siteLongitude: number;
}): string {
  return `# F5 XC Customer Edge — AWS
# Generated by F5 XC MCP Server
# Provider: volterraedge/volterra
# Reference: https://registry.terraform.io/providers/volterraedge/volterra/latest/docs

terraform {
  required_providers {
    volterra = {
      source  = "volterraedge/volterra"
      version = ">= 0.11"
    }
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0"
    }
  }
}

provider "volterra" {
  api_p12_file = var.api_p12_file
  url          = "https://${params.tenant}.console.ves.volterra.io/api"
}

provider "aws" {
  region = "${params.region}"
}

variable "api_p12_file" {
  description = "Path to F5 XC .p12 credentials file"
  type        = string
}

resource "volterra_aws_vpc_site" "${params.siteName.replace(/-/g, "_")}" {
  name      = "${params.siteName}"
  namespace = "system"

  aws_region = "${params.region}"

  vpc {
    vpc_id = "${params.vpcId}"
  }

  ingress_egress_gw {
    aws_certified_hw = "aws-byol-multi-nic-voltmesh"
    az_nodes {
      aws_az = "${params.region}a"
      disk_size = 80
      inside_subnet {
        existing_subnet_id = ""
      }
      outside_subnet {
        existing_subnet_id = ""
      }
      workload_subnet {
        existing_subnet_id = ""
      }
    }
  }

  coordinates {
    latitude  = ${params.siteLatitude}
    longitude = ${params.siteLongitude}
  }

  registration_token = "${params.token}"
}

output "site_name" {
  value = volterra_aws_vpc_site.${params.siteName.replace(/-/g, "_")}.name
}
`;
}

function generateGcpHcl(params: {
  tenant: string;
  siteName: string;
  token: string;
  region: string;
  projectId: string;
  vpcName: string;
  siteLatitude: number;
  siteLongitude: number;
}): string {
  return `# F5 XC Customer Edge — GCP
# Generated by F5 XC MCP Server
# Provider: volterraedge/volterra
# Reference: https://registry.terraform.io/providers/volterraedge/volterra/latest/docs

terraform {
  required_providers {
    volterra = {
      source  = "volterraedge/volterra"
      version = ">= 0.11"
    }
    google = {
      source  = "hashicorp/google"
      version = ">= 5.0"
    }
  }
}

provider "volterra" {
  api_p12_file = var.api_p12_file
  url          = "https://${params.tenant}.console.ves.volterra.io/api"
}

provider "google" {
  project = "${params.projectId}"
  region  = "${params.region}"
}

variable "api_p12_file" {
  description = "Path to F5 XC .p12 credentials file"
  type        = string
}

resource "volterra_gcp_vpc_site" "${params.siteName.replace(/-/g, "_")}" {
  name      = "${params.siteName}"
  namespace = "system"

  gcp_region  = "${params.region}"
  project_id  = "${params.projectId}"

  ingress_egress_gw {
    gcp_certified_hw = "gcp-byol-multi-nic-voltmesh"
    az_nodes {
      gcp_zone = "${params.region}-a"
      disk_size = 80
      inside_subnet {
        existing_subnet_name = "${params.vpcName}-inside"
      }
      outside_subnet {
        existing_subnet_name = "${params.vpcName}-outside"
      }
    }
  }

  coordinates {
    latitude  = ${params.siteLatitude}
    longitude = ${params.siteLongitude}
  }

  registration_token = "${params.token}"
}

output "site_name" {
  value = volterra_gcp_vpc_site.${params.siteName.replace(/-/g, "_")}.name
}
`;
}

export function registerCustomerEdgeTools(server: McpServer, client: F5XcClient, config: AppConfig): void {

  // ── CE Registration Tokens ─────────────────────────────────────────────────

  server.registerTool(
    "xc_ce_token_create",
    {
      title: "Create F5 XC CE Registration Token",
      description: `Create a Customer Edge (CE) registration token. The token is used by CE appliances or cloud VMs to self-register with the F5 XC tenant during deployment.

Tokens are single-use or time-limited — create one immediately before deploying a CE.

Args:
  - name: Token name (descriptive, e.g. "azure-ce-eastus-2024")
  - dryRun: Preview without executing`,
      inputSchema: z.object({
        name: z.string().min(1).describe("Registration token name (descriptive label)"),
        ...DryRunSchema,
      }).strict(),
      annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    },
    async ({ name, dryRun }) => {
      try {
        const result = await client.request({
          method: "POST",
          path: "/api/register/namespaces/system/tokens",
          body: { metadata: { name, namespace: "system" }, spec: {} },
          dryRun,
        });
        return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }], structuredContent: result as Record<string, unknown> };
      } catch (err) {
        return { content: [{ type: "text", text: handleApiError(err) }] };
      }
    },
  );

  // ── CE Site List / Status ──────────────────────────────────────────────────

  server.registerTool(
    "xc_ce_site_list",
    {
      title: "List F5 XC Customer Edge Sites",
      description: "List registered Customer Edge sites and their status. CEs self-register after deployment — use this to verify registration, check health, and review site metadata.",
      inputSchema: z.object({
        ...PaginationSchema,
      }).strict(),
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    },
    async ({ page_start, page_limit }) => {
      try {
        const result = await client.request({
          method: "GET",
          path: "/api/config/namespaces/system/sites",
          query: { page_start, page_limit },
        });
        return { content: [{ type: "text", text: truncate(JSON.stringify(result, null, 2)) }], structuredContent: result as Record<string, unknown> };
      } catch (err) {
        return { content: [{ type: "text", text: handleApiError(err) }] };
      }
    },
  );

  server.registerTool(
    "xc_ce_site_get",
    {
      title: "Get F5 XC Customer Edge Site",
      description: "Get the full status and spec of a Customer Edge site, including registration state, software version, connected REs, and network configuration.",
      inputSchema: z.object({
        name: z.string().min(1).describe("CE site name"),
      }).strict(),
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: true },
    },
    async ({ name }) => {
      try {
        const result = await client.request({ method: "GET", path: `/api/config/namespaces/system/sites/${encodeURIComponent(name)}` });
        return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }], structuredContent: result as Record<string, unknown> };
      } catch (err) {
        return { content: [{ type: "text", text: handleApiError(err) }] };
      }
    },
  );

  server.registerTool(
    "xc_ce_site_delete",
    {
      title: "Delete F5 XC Customer Edge Site",
      description: "Decommission a Customer Edge site. This removes the site from the F5 XC tenant. The actual cloud VM/appliance must be destroyed separately (e.g. via Terraform destroy). Ensure no HTTP LBs or services reference this site first.",
      inputSchema: z.object({
        name: z.string().min(1).describe("CE site name to decommission"),
        ...DryRunSchema,
      }).strict(),
      annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: true },
    },
    async ({ name, dryRun }) => {
      try {
        const result = await client.request({ method: "DELETE", path: `/api/config/namespaces/system/sites/${encodeURIComponent(name)}`, dryRun });
        return { content: [{ type: "text", text: JSON.stringify(result, null, 2) }], structuredContent: result as Record<string, unknown> };
      } catch (err) {
        return { content: [{ type: "text", text: handleApiError(err) }] };
      }
    },
  );

  // ── Terraform HCL Generation for CE Deployment ────────────────────────────

  server.registerTool(
    "xc_ce_tf_generate",
    {
      title: "Generate Terraform HCL for F5 XC Customer Edge",
      description: `Generate Terraform HCL for deploying a Customer Edge (CE) on Azure, AWS, or GCP using the volterraedge/volterra provider.

The generated HCL requires:
  1. A registration token from xc_ce_token_create
  2. terraform init && terraform apply
  3. The CE will self-register with F5 XC on first boot — verify with xc_ce_site_list

Args:
  - cloud: Target cloud provider (azure, aws, or gcp)
  - site_name: CE site name (must match what you want in F5 XC)
  - token: Registration token from xc_ce_token_create
  - region: Cloud region (e.g. eastus, us-east-1, us-central1)
  - site_latitude: Geographic latitude of the site (for proximity routing)
  - site_longitude: Geographic longitude of the site
  - azure_resource_group: (Azure only) Azure resource group name
  - azure_vnet_name: (Azure only) Existing VNet name
  - azure_subnet_name: (Azure only) Subnet name prefix (creates -inside and -outside subnets)
  - aws_vpc_id: (AWS only) Existing VPC ID
  - gcp_project_id: (GCP only) GCP project ID
  - gcp_vpc_name: (GCP only) GCP VPC name`,
      inputSchema: z.object({
        cloud: z.enum(["azure", "aws", "gcp"]).describe("Target cloud provider"),
        site_name: z.string().min(1).describe("CE site name in F5 XC"),
        token: z.string().min(1).describe("Registration token from xc_ce_token_create"),
        region: z.string().min(1).describe("Cloud region (e.g. eastus, us-east-1, us-central1)"),
        site_latitude: z.number().describe("Geographic latitude (-90 to 90)"),
        site_longitude: z.number().describe("Geographic longitude (-180 to 180)"),
        azure_resource_group: z.string().optional().describe("(Azure only) Azure resource group name"),
        azure_vnet_name: z.string().optional().describe("(Azure only) Existing VNet name"),
        azure_subnet_name: z.string().optional().describe("(Azure only) Subnet name prefix"),
        aws_vpc_id: z.string().optional().describe("(AWS only) Existing VPC ID"),
        gcp_project_id: z.string().optional().describe("(GCP only) GCP project ID"),
        gcp_vpc_name: z.string().optional().describe("(GCP only) GCP VPC name"),
      }).strict(),
      annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    },
    async ({ cloud, site_name, token, region, site_latitude, site_longitude, azure_resource_group, azure_vnet_name, azure_subnet_name, aws_vpc_id, gcp_project_id, gcp_vpc_name }) => {
      const tenant = config.tenant || "YOUR_TENANT";
      let hcl: string;

      if (cloud === "azure") {
        if (!azure_resource_group || !azure_vnet_name || !azure_subnet_name) {
          return { content: [{ type: "text", text: "Error: azure_resource_group, azure_vnet_name, and azure_subnet_name are required for Azure CE deployment." }] };
        }
        hcl = generateAzureHcl({ tenant, siteName: site_name, token, region, resourceGroup: azure_resource_group, vnetName: azure_vnet_name, subnetName: azure_subnet_name, siteLatitude: site_latitude, siteLongitude: site_longitude });
      } else if (cloud === "aws") {
        if (!aws_vpc_id) {
          return { content: [{ type: "text", text: "Error: aws_vpc_id is required for AWS CE deployment." }] };
        }
        hcl = generateAwsHcl({ tenant, siteName: site_name, token, region, vpcId: aws_vpc_id, siteLatitude: site_latitude, siteLongitude: site_longitude });
      } else {
        if (!gcp_project_id || !gcp_vpc_name) {
          return { content: [{ type: "text", text: "Error: gcp_project_id and gcp_vpc_name are required for GCP CE deployment." }] };
        }
        hcl = generateGcpHcl({ tenant, siteName: site_name, token, region, projectId: gcp_project_id, vpcName: gcp_vpc_name, siteLatitude: site_latitude, siteLongitude: site_longitude });
      }

      return { content: [{ type: "text", text: hcl }] };
    },
  );
}
